version: '3'

services:
  db:
    build: ./DB
    ports: 
      - "3306:3306"
    container_name: mysqldb
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: on-failure
    container_name: backend
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:3000"
    container_name: frontend
    stdin_open: true
    